### ISSUE TITLE
Missing dependencies in the Dockerfile

### ISSUE THREAD

**Issue by kukas** [exaexa/better-mff-thesis#12]
While debugging PDF/A compliance, I noticed that the provided Dockerfile misses some dependencies needed for compiling the template. Most importantly, it lacks `latexmk`, although there may be other missing packages. The recommended prebuilt image `aergus/latex` works as expected.

**Comment by exaexa** [comment]
good catch. I'm sure this worked at some point, perhaps latexmk was added as suggest-dependency there. Certainly not the case anymore, so I added it explicitly.
