### ISSUE TITLE
Potential violation of MFF style requirements for bibliography

### ISSUE THREAD

**Issue by oberth-effect** [exaexa/better-mff-thesis#13]
After using this thesis template, I got feedback from my Reviewer regarding the bibliography style; I set out to discover the requirements prescribed by MFF and found a potential conflict. This applies to both Czech and English language versions.
[Czech language details only]

### Problém
 Oponent (Fyzika) mi (u anglicky psané práce) vytkl, že v bibliografii, nejsou uvedena **všechna** jména autorů ale jsou zkracovány na et al..
Prošel jsem vnitřní předpisy fakulty, a myslím si, že existuje argument pro to, že je citační styl jasně definován jako "ten styl obsažený v oficiální šabloně".
 
 ### Relevantní dokumenty
 Konkrétní citační styl není explicitně definován ani ve [Směrnici děkana (SD) č. 1/2015](https://www.mff.cuni.cz/cs/vnitrni-zalezitosti/predpisy/opatreni-dekana/smernice-dekana-c-1-2015) ani v
 [SD č. 4/2019](https://www.mff.cuni.cz/cs/vnitrni-zalezitosti/predpisy/opatreni-dekana/smernice-dekana-c-4-2019).
 
SD č. 4/2019 však obsahuje článek 4.2:
> *Typografická úprava závěrečné práce musí odpovídat šabloně, která definuje požadovanou úpravu závěrečné práce. Tato šablona ve formátu RTF/LaTeX a ukázka jejího použití ve formátu PDF/A je studentům k dispozici ke stažení na webových stránkách fakulty.*

Oficiální TeXová šablona, tak jak je nakonfigurovaná v angličtině, tiskne všechna jména autorů (i 6+).
Česká rtf šablona obsahuje:
> Povinnou citační normou pro bakalářskou práci je ISO 690,

Anglická rtf šablona pak:

> A recommended citation standard for the bachelor thesis is ISO 690.

Podle referenčního stylu ISO 690:2021 se autoři mohou zkracovat jako "et. al." [sic!] nebo "and others" pro 6 a více autorů.

Situace je tedy značně nejednotná a nejasná. Existuje ale podle mě validní interpretace, že pro práce sázené v LaTeXu je podle SD č. 4/2019 je `natbib` `plainnat`/ `czplainnat` styl bibliografie a citací závazný.

### Návrh řešení
- Změnit šablonu tak, aby tisk **všech** autorů byl defaultní chování (minimálně do doby než se situace vyjasní).
- Iniciovat diskusi na úrovni vedení fakulty o upřesnění a lepší specifikaci "tvrdých" požadavků na úpravu kvalifikačních prací, neboť současná situace, kdy jsou studenti odkázáni na šablony, kde se mísí doporučené a nutné požadavky, navíc zcela nekonzistentně, není žádoucí.

### PS:
Určitě při řešení problému rád pomohu, ale nevím, na koho se obrátit, aby došlo k pozitivnímu posunu.
Rozhodně bych nerad, aby to vyústilo v deklaraci, že jiné, než oficiální šablony nejsou přípustné.
Better-mff-thesis mi ušetřila mnoho šedivých vlasů.
Studuji zároveň PFUK a "právní" analýza problému pochází čistě ode mě.

**Comment by exaexa** [comment]
Nazdar!
Nejde to opravit zapnutim neceho ze zakomentovanych moznosti zhruba tady?
https://github.com/exaexa/better-mff-thesis/blob/master/thesis.tex#L59
AFAIK iso 690 by pak melo fungovat automaticky spravne, navic by melo jit potunit pomoci neceho jako maxnames=6 nebo tak. (vic viz. `texdoc biblatex`).

Jestli to i s timhle optionem renderuje spatne, tak kdyztak prosim konkretni priklady bibtex entries+spravneho renderingu, at to mam na cem debugovat. (Pripadne jen staci potvrzeni jestli "oficialni" sablona je ta MJova.)

Diky!

**Comment by oberth-effect** [comment]
Ahoj,
'oficiální šablonou' myslím [to](https://www.mff.cuni.cz/studium/bcmgr/prace/vzor-bp.zip) co člověk stáhne [na stránkách MFF.](https://www.mff.cuni.cz/cs/studenti/bc-a-mgr-studium/bakalarske-a-diplomove-prace)

Zbuildění z možností [iso-numeric](https://github.com/exaexa/better-mff-thesis/blob/master/thesis.tex#L59) zdá se, generuje to chování co si asi můj oponent představoval - tj. všichni autoři v Bibliografii. 
(Jediné neergonomické je, že `\citet{ref}` pak vygeneruje wall of text)
Nevím, jaký je na MFF obecně na tohle názor, a jestli se výrazně liší mezi sekcema, ale asi bych navrhnul to udělat jako základní možnost, ať mají lidé jistotu, že je nebude někdo tahat na malichernostech.

**Comment by exaexa** [comment]
Na informatice prave vetsinou delame tu "defaultni" protoze iso je dost neprakticky a nepouziva ho skoro zadnej realnej zurnal. Jinak jsem asi pro lepsi default, minimalne durazne zvyraznim moznost mit ISO690.

btw. \citet jde znormalizovat necim jako maxcitenames=2, pomuze to?

**Comment by oberth-effect** [comment]
Chápu, tahle revoluce asi na Fyziku ještě nedorazila. 🙃
Pokud se nebude měnit default templatu, tak bych alespoň odstranil [tuhle větu](https://github.com/exaexa/better-mff-thesis/blob/master/thesis.tex#L58):
> (iso690 is not formally required on MFF, but may help elsewhere):

A naopak napsal nějaké důrazné upozornění, že v závislosti na sekci/specializaci/whatever by si měl autor zkontrolovat jestli nevyžadují ISO690. Nedávno jsem doporučoval tenhle template několika kolegům z Fyziky, tak bych nerad aby v případě, že se to bude šířit měli problémy.

Já jsem se bohužel spolehl na to, že to nikde explicitně napsané není, a byla to chyba.
Nevím, jestli by se nějak dalo zatlačit na relevantní osoby, aby se buď změnil, nebo alespoň specifikoval tenhle detail, protože to je fakt úplně zbytečné přetahování se s oponentem potom...

`maxcitenames` funguje perfektně :)

**Comment by exaexa** [comment]
OK super. Mam tam dat to finalni nastaveni? (jestli to dobre chapu tak "dobra" verze je `style=iso-numeric,maxnames=6,maxcitenames=2`, sedi?)

Jinak oponent do toho asi muze rejt, ale pochybuju ze by to melo mit dopad na vysledek obhajoby (nejsme Ustav Formalni Kompatibility). Hlavne kdyz prebuildit v ISO to trva asi tak 5 sekund a v krajnim pripade se ISO verze prace/referenci da pripojit jako erratum.
