### ISSUE TITLE
Stress the use of LuaLatex in README

### ISSUE THREAD

**Issue by petrkasp** [exaexa/better-mff-thesis#19]
Hi,

due to the new verification profile, I am not able to pass the verification with pdfLatex and the font Libertinus. I know the Makefile and so on use LuaLatex, but I was not aware of that and built the thesis while using pdfLatex on Overleaf and now I need to change, which is highly unpleasant. Also, I ended up using XeLaTeX in the end.

I suggest highlighting the need to use LuaLaTeX (or XeLaTeX) in the readme.

Thanks,
Peter

**Comment by exaexa** [comment]
true, will try to do asap. Feel free to send PR suggestions

(btw. maybe the whole pdflatex should have this sorta "unmaintained" label atop of it :D )

**Comment by petrkasp** [comment]
> (btw. maybe the whole pdflatex should have this sorta "unmaintained" label atop of it :D )

Thanks for the info. From Mařeš's website, I got the impression that you actually need to use pdflatex and not anything else:

> PDF/A-1a v TeXu sázet prakticky nelze, PDF/A-2u s trochou snahy funguje. Je potřeba dostatečně nový pdfLaTeX s aktuálním balíčkem pdfx.
>
>- Ne-PDFkový LaTeX nelze použít.

**Comment by exaexa** [comment]
hm yeah that sounds more like a warning against the older dvi/ps pipeline with plain `latex` (which is unable to produce pdf/A for technical reasons).

If the naming scheme was a little more systematic, `lualatex` would be more like `luapdflatex`. Not sure where XeTeX stands in these but I'd say it's also sufficiently PDF-ish.
