### ISSUE TITLE
The floatrow package causes all table captions to be below the table.

### ISSUE THREAD

**Issue by gabikadlecova** [exaexa/better-mff-thesis#2]
In publications, the standard is to have table captions positioned above, and figure captions below. However, the floatrow package overrides the behavior by always positioning the table caption below.

Possible solution is to add `\floatsetup[table]{capposition=top}` to thesis.tex. The floatrow package is used in macros.tex for the definition of some caption styles, and also code and code listing, so it cannot be simply removed.

Will make an PR for the optional `\floatsetup` after the deadline (I'm writing this issue mainly in case somebody else had the same problem as me).

**Comment by exaexa** [comment]
Good point, I'll have a look. The `float` package should be able to do that.

**Comment by exaexa** [comment]
( Side story:

This has been pointed out a few times, BUT I've got a pretty unpopular but very™ true™ opinion™ that all table captions should be below the tables. In short, above captions 1] should actually be headings (bold) 2] clash with column headings which should always form the easily visible "top line", because reader's eyes need to jump there often.

)

**Comment by gabikadlecova** [comment]
Well, I have a different™ also true™ opinion™ that the above caption makes sense, since 2) I first read what the table is about and then look at the values (if it were a long table, one would have to scroll all the way down), and 1) the table captions are quite small, so it doesn't clash with the titles imo.

However regardless of which opinion is true(er), I think the caption should be above in the template so that the students have it as expected, otherwise some opponents could see it as an error.

**Comment by exaexa** [comment]
> 1) the table captions are quite small,

heading spotted! :grin: 

> scroll all the way down

ah okay, it certainly makes better sense on small screens.

Can you check if the linked PR looks okay? (I'll add extra commentary)

**Comment by gabikadlecova** [comment]
PR looks good now. I'm closing the issue.
